version: 2
build:
  os: ubuntu-22.04
  tools:
    python: mambaforge-4.10
sphinx:
  configuration: docs/conf.py
python:
  install:
  - method: pip
    path: .
conda:
  environment: environment.yml
formats:
- pdf
