version: '3'
services:
  work:
    build: .
    volumes:
      - .:/app
    network_mode: host
    pid: host
    privileged: true
    cap_add:
      - SYS_PTRACE

  workmac:
    build: .
    volumes:
      - .:/app
    network_mode: bridge
    pid: host
    privileged: true
    cap_add:
      - SYS_PTRACE
