name: Run linter in Docker image
description: Run private container from GitHub Packages Registry after Docker login
runs:
  using: 'docker'
  image: docker.pkg.github.com/quantco/miniforge3-qc-dev/miniconda3-qc-base:latest
  args:
   - /bin/bash
   - "-l"
   - "-c"
   - "./.github/workflows/pre-commit.sh"
