name: Run linter in Docker image
description: Run private container from GitHub Packages Registry after Docker login
runs:
  using: 'docker'
  image: condaforge/mambaforge:latest
  args:
   - /bin/bash
   - "-l"
   - "-c"
   - "./.github/workflows/pre-commit.sh"
