name: Run CD inside of container
description: Deploy package from the private container from GitHub Packages Registry after Docker login
inputs:
  conda_build_yml:
    description: "conda-build variant file"
    required: true
runs:
  using: 'docker'
  image: condaforge/mambaforge:latest
  args:
   - /bin/bash
   - "-l"
   - "-c"
   - "./.github/workflows/tag.sh ${{ inputs.conda_build_yml }}"
