{% set build_number = "0" %}
{% set build_string = "py{}h{}_{}_{}".format(CONDA_PY, PKG_HASH, build_number, GLM_ARCHITECTURE) %}

package:
  name: glum
  version: {{ environ.get('GIT_DESCRIBE_TAG', '').lstrip('v') }}{% if environ.get('GIT_DESCRIBE_NUMBER', 0)|int != 0 %}.post{{ GIT_DESCRIBE_NUMBER }}+{{ GIT_DESCRIBE_HASH }}{% endif %}

source:
  git_url: ../


build:
  number: {{ build_number }}
  string: "{{ build_string }}"
  track_features:
    {{ "- glum-{}".format(GLM_ARCHITECTURE) if GLM_ARCHITECTURE != "default" else "" }}


requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - llvm-openmp  # [osx]
  host:
    - python
    - cython
    - llvm-openmp  # [osx]
    - numpy
    - pip
    - scikit-learn >=0.23
    - setuptools_scm
  run:
    - python
    - joblib
    - numexpr
    - {{ pin_compatible('numpy') }}
    - pandas
    - scikit-learn >=0.23
    - scipy
    - tabmat >=3.0.1

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - glum

about:
  home: https://github.com/Quantco/glum
  license: Proprietary
