name: conda-build Linux
on:
  push:
    branches:
      - main
jobs:
  linux-conda-build:
    name: Python ${{ matrix.CONDA_BUILD_YML }}
    runs-on: ubuntu-latest
    env:
      CI: True
    strategy:
      fail-fast: true
      matrix:
        CONDA_BUILD_YML:
          - linux_64_numpy1.20python3.8.____cpython
          - linux_64_numpy1.20python3.9.____cpython
          - linux_64_numpy1.23python3.11.____cpython
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
      - name: Fetch full git history
        run: git fetch --prune --unshallow
      - uses: mamba-org/setup-micromamba@875557da4ee020f18df03b8910a42203fbf02da1
        with:
          environment-name: build
          create-args: boa
      - name: Build conda package
        shell: bash -el {0}
        run: conda-mambabuild -m ".ci_support/${{ matrix.CONDA_BUILD_YML }}.yaml" conda.recipe
