name: conda-build Windows
on:
  push:
    paths:
      - '.github/**'
      - 'conda.recipe/**'
jobs:
  windows-conda-build:
    name: Python ${{ matrix.CONDA_BUILD_YML }}
    runs-on: windows-latest
    env:
      CI: True
      CONDA_BUILD_YML: "${{ matrix.CONDA_BUILD_YML }}"
    strategy:
      fail-fast: false
      matrix:
        CONDA_BUILD_YML:
          - win_64_numpy1.20python3.8.____cpython
          - win_64_numpy1.23python3.11.____cpython
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
      - name: Fetch full git history
        run: git fetch --prune --unshallow
      - uses: mamba-org/setup-micromamba@875557da4ee020f18df03b8910a42203fbf02da1
        with:
          init-shell: cmd.exe
          environment-name: build
          create-args: boa
      - name: DEBUG
        shell: cmd /C CALL {0}
        run: micromamba info
      - name: Build conda package
        shell: cmd /C CALL {0}
        run: conda-mambabuild -m ".ci_support/${{ matrix.CONDA_BUILD_YML}}.yaml" conda.recipe
