name: conda-build Windows
on:
  push:
    paths:
      - '.github/**'
      - 'conda.recipe/**'
jobs:
  windows-conda-build:
    name: "Windows - conda-build - ${{ matrix.CONDA_BUILD_YML }}"
    runs-on: windows-latest
    env:
      CI: True
      CONDA_BUILD_YML: "${{ matrix.CONDA_BUILD_YML }}"
    strategy:
      fail-fast: false
      matrix:
        CONDA_BUILD_YML:
          - win_64_numpy1.20python3.8.____cpython
          - win_64_numpy1.23python3.11.____cpython
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Fetch full git history
        run: git fetch --prune --unshallow
      - uses: conda-incubator/setup-miniconda@3b0f2504dd76ef23b6d31f291f4913fb60ab5ff3
        with:
          miniforge-variant: Mambaforge
          miniforge-version: 4.14.0-2
          use-mamba: true
      - name: Build conda package
        shell: pwsh
        run: |
          mamba install -n base -y boa
          conda mambabuild -m .ci_support/${{ matrix.CONDA_BUILD_YML}}.yaml conda.recipe
