name: conda-build Windows
on:
  push:
    paths:
      - '.github/**'
      - 'conda.recipe/**'
jobs:
  windows-conda-build:
    name: "Windows - conda-build - ${{ matrix.CONDA_BUILD_YML }}"
    runs-on: windows-latest
    env:
      CI: True
      CONDA_CHANNEL_UPLOAD_USER: ${{ secrets.CONDA_CHANNEL_UPLOAD_USER }}
      CONDA_CHANNEL_UPLOAD_PASSWORD: ${{ secrets.CONDA_CHANNEL_UPLOAD_PASSWORD }}
      CONDA_BUILD_YML: "${{ matrix.CONDA_BUILD_YML }}"
    strategy:
      fail-fast: false
      matrix:
        CONDA_BUILD_YML:
          - win_64_python3.6.____cpython
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2.3.4
        with:
          ref: ${{ github.head_ref }}
      - name: Fetch full git history
        run: git fetch --prune --unshallow
      - name: Create .condarc
        shell: pwsh
        run: |
          ((Get-Content -path .github/workflows/.condarc) -replace 'CONDA_CHANNEL_UPLOAD_USER', '${{ secrets.CONDA_CHANNEL_UPLOAD_USER }}') | Set-Content .github/workflows/.condarc
          ((Get-Content -path .github/workflows/.condarc) -replace 'CONDA_CHANNEL_UPLOAD_PASSWORD', '${{ secrets.CONDA_CHANNEL_UPLOAD_PASSWORD }}') | Set-Content .github/workflows/.condarc
      - uses: conda-incubator/setup-miniconda@723ab12c1d66bb893c5ac701f8e387f00b24549e
        with:
          miniforge-variant: Mambaforge
          miniforge-version: 4.10.0-0
          use-mamba: true
          condarc-file: .github/workflows/.condarc
      - name: Build conda package
        shell: pwsh
        run: |
          mamba install -n base -y conda-build
          conda build -m .ci_support/${{ matrix.CONDA_BUILD_YML}}.yaml conda.recipe

