name: CI - macOS
on:
  push:
    branches:
      - main
    paths:
      - '.github/**'
      - '**/*.pyx'
      - '**/*.cpp'
      - 'setup.py'
      - 'environment.yml'
      - 'environment-benchmark.yml'

jobs:
  macos:
    name: macOS - tests - Python ${{ matrix.PYTHON_VERSION }}
    runs-on: macos-latest
    env:
      CI: True
      PYTHON_VERSION: ${{ matrix.PYTHON_VERSION }}
    strategy:
      fail-fast: true
      matrix:
        PYTHON_VERSION: ['3.10']
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - uses: mamba-org/setup-micromamba@875557da4ee020f18df03b8910a42203fbf02da1
        with:
          environment-file: environment.yml
          create-args: >- # h2o-py and openjdk from environment-benchmark.yml
            python=${{ matrix.PYTHON_VERSION }}
            h2o-py
            openjdk
      - name: Install repository
        shell: bash -l {0}
        run: pip install --no-use-pep517 --no-deps --disable-pip-version-check -e .
      - name: Run pytest
        shell: bash -l {0}
        run: pytest -nauto tests --doctest-modules src/glum/
