name: CI
on:
  push:
    paths:
      - '.github/**'
      - '**/*.pyx'
      - '**/*.cpp'

jobs:
  macos:
    name: "MacOS - tests - Python ${{ matrix.PYTHON_VERSION }}"
    runs-on: macos-latest
    env:
      CI: True
      CONDA_CHANNEL_UPLOAD_USER: ${{ secrets.CONDA_CHANNEL_UPLOAD_USER }}
      CONDA_CHANNEL_UPLOAD_PASSWORD: ${{ secrets.CONDA_CHANNEL_UPLOAD_PASSWORD }}
      PYTHON_VERSION: ${{ matrix.PYTHON_VERSION }}
    strategy:
      fail-fast: true
      matrix:
        PYTHON_VERSION: ['3.7']
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2.1.0
        with:
          ref: ${{ github.head_ref }}
      - name: Create .condarc
        shell: bash -l {0}
        run: |
          sed -ie "s/CONDA_CHANNEL_UPLOAD_USER/${CONDA_CHANNEL_UPLOAD_USER}/g" .github/workflows/.condarc
          sed -ie "s/CONDA_CHANNEL_UPLOAD_PASSWORD/${CONDA_CHANNEL_UPLOAD_PASSWORD}/g" .github/workflows/.condarc
        env:
          CONDA_CHANNEL_UPLOAD_USER: ${{ secrets.CONDA_CHANNEL_UPLOAD_USER }}
          CONDA_CHANNEL_UPLOAD_PASSWORD: ${{ secrets.CONDA_CHANNEL_UPLOAD_PASSWORD }}
      - uses: conda-incubator/setup-miniconda@v2
        with:
          installer-url: https://github.com/conda-forge/miniforge/releases/download/4.9.0-4/Miniforge3-4.9.0-4-MacOSX-x86_64.sh
          mamba-version: "*"
          allow-softlinks: true
          show-channel-urls: true
          use-only-tar-bz2: true
          channels: quantco_main,conda-forge
          condarc-file: .github/workflows/.condarc
      - name: Run Unit Tests
        shell: bash -l {0}
        run: ./.github/workflows/macos.sh
