name: CI - macOS
on:
  push:
    paths:
      - '.github/**'
      - '**/*.pyx'
      - '**/*.cpp'
      - 'setup.py'
      - 'environment.yml'
      - 'environment-benchmark.yml'

jobs:
  macos:
    name: "MacOS - tests - Python ${{ matrix.PYTHON_VERSION }}"
    runs-on: macos-latest
    env:
      CI: True
      PYTHON_VERSION: ${{ matrix.PYTHON_VERSION }}
    strategy:
      fail-fast: true
      matrix:
        PYTHON_VERSION: ['3.10']
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - uses: conda-incubator/setup-miniconda@3b0f2504dd76ef23b6d31f291f4913fb60ab5ff3
        with:
          miniforge-variant: Mambaforge
          miniforge-version: 4.10.0-0
          use-mamba: true
      - name: Run Unit Tests
        shell: bash -l {0}
        run: ./.github/workflows/macos.sh
