name: CI
on:
  push:
    paths:
      - '.github/**'
      - '**/*.pyx'
      - '**/*.cpp'
jobs:
  windows-ci:
    name: "Win - tests - Python ${{ matrix.PYTHON_VERSION }}"
    runs-on: windows-latest
    env:
      CI: True
    strategy:
      fail-fast: true
      matrix:
        PYTHON_VERSION: ['3.7']
    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
      - name: Checkout branch
        uses: actions/checkout@v2.3.5
        with:
          ref: ${{ github.head_ref }}
      - uses: conda-incubator/setup-miniconda@35d1405e78aa3f784fe3ce9a2eb378d5eeb62169
        with:
          python-version: ${{ matrix.PYTHON_VERSION }}
          miniforge-variant: Mambaforge
          miniforge-version: 4.10.0-0
          use-mamba: true
          environment-file: environment.yml
          activate-environment: glum
      - name: Install benchmark dependencies
        shell: pwsh
        run: |
          mamba env update -n glum --file environment-benchmark.yml
      - name: Run Unit Tests
        shell: pwsh
        run: |
          python -m pip install -e . --no-deps -vv --no-use-pep517 --disable-pip-version-check
          pytest tests --doctest-modules src/
