name: CI - Windows
on:
  push:
    branches:
      - main
    paths:
      - '.github/**'
      - '**/*.pyx'
      - '**/*.cpp'
      - 'setup.py'
      - 'environment.yml'
      - 'environment-benchmark.yml'
      
jobs:
  windows-ci:
    name: "Win - tests - Python ${{ matrix.PYTHON_VERSION }}"
    runs-on: windows-latest
    env:
      CI: True
    strategy:
      fail-fast: true
      matrix:
        PYTHON_VERSION: ['3.10']
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
      - uses: mamba-org/setup-micromamba@875557da4ee020f18df03b8910a42203fbf02da1
        with:
          environment-file: environment.yml
          init-shell: powershell
          create-args: >- # h2o-py and openjdk from environment-benchmark.yml
            python=${{ matrix.PYTHON_VERSION }}
            h2o-py
            openjdk
      - name: Install repository
        shell: powershell
        run: python -m pip install -e . --no-deps -vv --no-use-pep517 --disable-pip-version-check
      - name: Run pytest
        shell: powershell
        run: pytest tests --doctest-modules src/glum
