name: Run image
description: Run private container from GitHub Packages Registry after Docker login
inputs:
  conda_build_yml:
    description: "conda-build variant file"
    required: true
runs:
  using: 'docker'
  image: docker.pkg.github.com/quantco/miniforge3-qc-dev/miniconda3-qc-base:latest
  args:
   - /bin/bash
   - "-l"
   - "-c"
   - "./.github/workflows/conda-build.sh ${{ inputs.conda_build_yml }}"
